FROM node:18

WORKDIR /usr/src/app

COPY . .

# npm install is not needed because it is supposed to run locally
# RUN npm install

CMD ["/bin/bash","-c","chmod +x ./entrypoint.test.sh && ./entrypoint.test.sh"]
